site_name: Flexible Lists of Values (LOV) for Django
site_url: https://github.com/jacklinke/flexible-list-of-values
site_description: Docs for flexible-list-of-values
site_footer: 
site_author: Jack Linke

copyright: Copyright © 2022 Jack All Rights Reserved.

repo_name: flexible-list-of-values
repo_url: https://github.com/jacklinke/flexible-list-of-values

dev_addr: 127.0.0.1:8070

theme:
  logo: assets/logo.svg
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
  font:
    text: Helvetica
  name: material
  custom_dir: docs/overrides
  static_templates:
    - 404.html
  features:
    - content.code.annotate
    - navigation.indexes
    - navigation.tabs
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - media: "(prefers-color-scheme: light)" # 
      scheme: light
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" # 
      scheme: dark
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.extra
  - meta

plugins:
  - autorefs
  - search
  - gen-files:
      scripts:
      - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_heading: true
            # show_object_full_path: true
            # show_category_heading: true
            show_if_no_docstring: true
          setup_commands:
            - import os
            - import sys
            - import django
            - sys.path.insert(0, os.path.abspath("flexible_list_of_values/"))
            - os.environ.setdefault("DJANGO_SETTINGS_MODULE", "tests.settings")
            - django.setup()
      watch:
        - .
      enable_inventory: true
  - mike:
      canonical_version: "2.7"
  

nav:
  - Documentation: 
    - Usage:
      - Installation: usage/installation.md
      - Getting Started: usage/getting_started.md
    - Contributing: contributing.md
    - Reference: reference/
